jobs:
  rules:
    tpv_rules_local.yml:
      global:
        default_inherits: default
      tools:
        default:
          cores: 24
          mem: 100
          params:
            local_slots: "32"
          scheduling:
            reject:
              - local
              - offline
      destinations:
        k8s:
          params:
            requests_cpu: "32"
            requests_memory: "100Gi"
            limits_cpu: "32"
            limits_memory: "100Gi"
          scheduling:
            accept:
              - docker
        local:
          scheduling:
            require:
              - local
