jobs:
  rules:
    tpv_rules_local.yml:
      global:
        default_inherits: default
      tools:
        default:
          cores: 4
          mem: 8
          params:
            local_slots: "4"
          scheduling:
            reject:
              - local
              - offline
      destinations:
        k8s:
          params:
            requests_cpu: "4"
            requests_memory: "8Gi"
            limits_cpu: "4"
            limits_memory: "8Gi"
          scheduling:
            accept:
              - docker
        local:
          scheduling:
            require:
              - local
