jobs:
  rules:
    tpv_rules_local.yml:
      global:
        default_inherits: default
      tools:
        default:
          cores: 8
          mem: 32
          params:
            local_slots: "8"
          scheduling:
            reject:
              - local
              - offline
      destinations:
        k8s:
          params:
            requests_cpu: "8"
            requests_memory: "32Gi"
            limits_cpu: "8"
            limits_memory: "32Gi"
          scheduling:
            accept:
              - docker
        local:
          scheduling:
            require:
              - local
